# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-18 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='Comment',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
