# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-11-20 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Medicament', '0001_initial'),
        ('cart', '0002_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Medicaments',
            field=models.ManyToManyField(blank=True, to='Medicament.Medicament'),
        ),
    ]
